# Generated by Django 3.1.5 on 2021-02-04 03:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('api_key', models.CharField(max_length=60, unique=True)),
                ('secret_key', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=api.models.generate_unique_id, max_length=8, unique=True)),
                ('ticker', models.CharField(default='', max_length=5)),
                ('owner', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(default='', max_length=15)),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stop_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trail_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_in_force', models.CharField(default='day', max_length=5)),
            ],
        ),
    ]
