# Generated by Django 3.1.5 on 2021-02-02 05:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=api.models.generate_unique_id, max_length=8, unique=True),
        ),
    ]
