# Generated by Django 3.1.5 on 2021-02-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
