# Generated by Django 3.1.5 on 2021-02-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='order_type',
        ),
    ]
