# Generated by Django 3.1.5 on 2021-02-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210203_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='stop_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='trail_percent',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='trail_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
    ]
