# Generated by Django 3.1.5 on 2021-02-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210203_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_in_force',
            field=models.CharField(default='day', max_length=5),
        ),
    ]
